import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    paddingBottom: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 4,
  },
  meta: {
    color: "#666",
    fontSize: 10,
    marginBottom: 2,
  },
  statusBadge: {
    fontSize: 10,
    color: "#fff",
    backgroundColor: "#333",
    padding: "2 8",
    borderRadius: 4,
    alignSelf: "flex-start",
  },
  content: {
    marginTop: 16,
    lineHeight: 1.6,
  },
  section: {
    marginBottom: 12,
  },
  signersSection: {
    marginTop: 32,
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    paddingTop: 16,
  },
  signerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingVertical: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  signerName: {
    fontSize: 11,
    fontWeight: "bold",
  },
  signerStatus: {
    fontSize: 10,
    color: "#666",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
    borderTopWidth: 0.5,
    borderTopColor: "#eee",
    paddingTop: 8,
  },
});

interface ContractPdfProps {
  title: string;
  type: string;
  status: string;
  content: string;
  signers: Array<{ name: string; email: string; status: string; signedAt?: string }>;
  dateSent?: string;
  dateSigned?: string;
}

function stripHtml(html: string): string {
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function ContractDocument({
  title,
  type,
  status,
  content,
  signers,
  dateSent,
  dateSigned,
}: ContractPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.meta}>
            {type.charAt(0).toUpperCase() + type.slice(1)}
          </Text>
          <Text style={styles.meta}>
            Status: {status.charAt(0).toUpperCase() + status.slice(1)}
          </Text>
          {dateSent && <Text style={styles.meta}>Sent: {dateSent}</Text>}
          {dateSigned && <Text style={styles.meta}>Signed: {dateSigned}</Text>}
        </View>

        <View style={styles.content}>
          <Text>{stripHtml(content) || "No content."}</Text>
        </View>

        {signers.length > 0 && (
          <View style={styles.signersSection}>
            <Text style={{ fontSize: 14, fontWeight: "bold", marginBottom: 12 }}>
              Signatures
            </Text>
            {signers.map((signer, i) => (
              <View key={i} style={styles.signerRow}>
                <View>
                  <Text style={styles.signerName}>{signer.name}</Text>
                  <Text style={{ fontSize: 9, color: "#999" }}>{signer.email}</Text>
                </View>
                <Text style={styles.signerStatus}>
                  {signer.status === "signed" ? "✓ Signed" : "Pending"}
                  {signer.signedAt ? ` (${signer.signedAt})` : ""}
                </Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>
          Generated by LeadFlow CRM | {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function generateContractPdf(data: ContractPdfProps): Promise<Blob> {
  const doc = <ContractDocument {...data} />;
  const blob = await pdf(doc).toBlob();
  return blob;
}
